---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Runs on a new pull request, performs build and runs tests
name: 'Python Build/Test/Release'

# yamllint disable-line rule:truthy
on:
  # Trigger on tag push events
  push:
    tags:
      - '**'

permissions: {}

jobs:
  tag-validate:
    name: 'Validate Tag Push'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
    timeout-minutes: 1
    outputs:
      tag: "${{ steps.tag-validate.outputs.tag }}"
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: 'audit'

      - name: 'Verify Pushed Tag'
        id: 'tag-validate'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/tag-push-verify-action@80e2bdbbb9ee7b67557a31705892b75e75d2859e # v0.1.1
        with:
          versioning: 'semver'

      - name: 'Reject Development Tags'
        if: steps.tag-validate.outputs.dev_version == 'true'
        shell: bash
        run: |
          # Reject Development Tags
          echo "Development tag pushed; aborting release workflow ðŸ›‘"
          echo "Development tag pushed; aborting release workflow ðŸ›‘" \
            >> "$GITHUB_STEP_SUMMARY"
          exit 1

  python-build:
    name: 'Python Build'
    needs: 'tag-validate'
    runs-on: 'ubuntu-latest'
    outputs:
      matrix_json: "${{ steps.python-build.outputs.matrix_json }}"
      artefact_name: "${{ steps.python-build.outputs.artefact_name }}"
      artefact_path: "${{ steps.python-build.outputs.artefact_path }}"
    permissions:
      contents: read
      id-token: write       # Needed for attestations
      attestations: write   # Needed for attestations
    timeout-minutes: 12
    env:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: 'audit'

      # yamllint disable-line rule:line-length
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 'Build Python project'
        id: 'python-build'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/python-build-action@3552106f5c8bfedebe4c38116abf3b9c289359ea # v0.1.22
        with:
          sigstore_sign: true
          attestations: true

  python-tests:
    name: 'Python Tests'
    runs-on: 'ubuntu-latest'
    needs: 'python-build'
    # Matrix job
    strategy:
      fail-fast: false
      matrix: "${{ fromJson(needs.python-build.outputs.matrix_json) }}"
    permissions:
      contents: read
    timeout-minutes: 12
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      # yamllint disable-line rule:line-length
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 'Test Python project [PYTEST]'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/python-test-action@0e430cc107b7b38edc42616d3542b38835d25014 # v1.0.0
        with:
          python_version: "${{ matrix.python-version }}"

  python-audit:
    name: 'Python Audit'
    runs-on: 'ubuntu-latest'
    needs: 'python-build'
    # Matrix job
    strategy:
      fail-fast: false
      matrix: "${{ fromJson(needs.python-build.outputs.matrix_json) }}"
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: 'audit'

      # yamllint disable-line rule:line-length
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 'Audit Python project'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/python-audit-action@d2a271bdbf08572dbd8addd3358e5e937ab3739b # v0.2.3
        with:
          python_version: "${{ matrix.python-version }}"

  test-pypi:
    name: 'Test PyPI Publishing'
    runs-on: 'ubuntu-latest'
    needs:
      - 'tag-validate'
      - 'python-tests'
      - 'python-audit'
    environment:
      name: 'development'
    permissions:
      contents: read
      id-token: write # IMPORTANT: mandatory for trusted publishing
    timeout-minutes: 5
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: 'audit'

      # yamllint disable-line rule:line-length
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 'Test PyPI publishing'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/pypi-publish-action@440c499c2ba633f95a281c02e624676e753d01ea # v0.1.3
        with:
          environment: 'development'
          tag: "${{ needs.tag-validate.outputs.tag }}"

  pypi:
    name: 'Release PyPI Package'
    runs-on: 'ubuntu-latest'
    needs:
      - 'tag-validate'
      - 'test-pypi'
    environment:
      name: 'production'
    permissions:
      contents: read
      id-token: write # IMPORTANT: mandatory for trusted publishing
    timeout-minutes: 5
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: 'audit'

      # yamllint disable-line rule:line-length
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 'PyPI release'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/pypi-publish-action@440c499c2ba633f95a281c02e624676e753d01ea # v0.1.3
        with:
          environment: 'production'
          attestations: true
          tag: "${{ needs.tag-validate.outputs.tag }}"

  promote-release:
    name: 'Promote Draft Release'
    # yamllint disable-line rule:line-length
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - 'tag-validate'
      - 'pypi'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write # IMPORTANT: needed to edit a draft release and promote it
    timeout-minutes: 2
    outputs:
      release_url: "${{ steps.promote-release.outputs.release_url }}"
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: 'audit'

      # yamllint disable-line rule:line-length
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 'Promote draft release'
        id: 'promote-release'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/draft-release-promote-action@cd7cf442875ecaea5dbb070d0de94f21ece107c8 # v0.1.3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ needs.tag-validate.outputs.tag }}"
          latest: true

  # Need to attach build artefacts to the release
  # This step could potentially be moved
  # (May be better to when/where the release is still in draft state)
  attach-artefacts:
    name: 'Attach Artefacts to Release'
    runs-on: 'ubuntu-latest'
    needs:
      - 'tag-validate'
      - 'python-build'
      - 'promote-release'
    permissions:
      contents: write # IMPORTANT: needed to edit release, attach artefacts
    timeout-minutes: 5
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: 'audit'

      # Note: no need for a checkout step in this job

      - name: 'â¬‡ Download build artefacts'
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: "${{ needs.python-build.outputs.artefact_name }}"
          path: "${{ needs.python-build.outputs.artefact_path }}"

      - name: 'Attach build artefacts to release'
        # yamllint disable-line rule:line-length
        uses: alexellis/upload-assets@13926a61cdb2cb35f5fdef1c06b8b591523236d3 # 0.4.1
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        with:
          asset_paths: '["${{ needs.python-build.outputs.artefact_path }}/**"]'
